config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#home'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get 'welcome/:first_name', to: 'dynamic#welcome', as: 'welcome_first_name'
  get 'home/:id', to: 'dynamic#user', as: 'user'
  
  resources :gossips
  resources :cities
  resources :comments
  resources :users, only:[:new,:create,:show]
  resources :sessions, only:[:new,:create,:destroy]
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags
  has_many :comments
  
  validates :title, 
    presence: true,
    length: { in: 3..14}
  validates :content, presence: true

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @gossip = Gossip.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    @gossip = Gossip.new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    u = User.first
    puts "Regardee"
    @gossip = Gossip.new
    @gossip.title = (params["title"])
    @gossip.content = (params["content"])
    @gossip.user = u
    
    if @gossip.save 
      flash[:success] = "Ton super potin est en ligne."
      redirect_to "/"
    else
      render "new"
    end
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end
  
  

  def edit
    @gossip = Gossip.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(gossip_params)
      flash[:success] = "Tu as bien modifié le potin"
      redirect_to gossip_path
    else
      render :edit
    end
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    flash[:success] = "Tu as bien supprimé le potin"
    redirect_to root_path
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/views/gossips/edit.html.erb
<%if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à modifier le potin : </p>
    <ul><li>Les champs titre et contenu doivent être obligatoirement remplis
    <li>Le titre du Gossip doit contenir entre 3 et 14 caractères
    </ul>
  </div><br />
<% end %>


<h1> Editer le potin </h1>

<% gossip = Gossip.find(params[:id]) %>

<%= form_for gossip do |f| %>

  <div class="form-group">
  <label>Titre du gossip</label>
  <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
  <label>Contenu du gossip</label>
  <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
  <button type="submit" class = "btn btn-primary"  >Modifier l'article</button>
  </div>

<% end %>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<h1> Créer un gossip</h1>



<form action= <%= gossips_path %> method="POST">
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
       Ton titre :   
      <input type="string" name="title"><br><br>
      Ton potin :
      <input type="text" name="content"><br><br>
      <input type="submit" value="Balance ton potin">
</form>

app/views/gossips/show.html.erb
<% if flash[:success] %>
   <div class="alert alert-success" role="alert">
   <h4 class="alert-heading">SUPER</h4>
   <hr>
   <div class=“success”><%= flash[:success]%></div>
   </div>
 <% end %>

<br> <br><h2>PAGE POTIN </h2>

<br>
  <p> Voici le potin n° <%= @gossip.id%><br/><br>
  L'auteur : <%= @gossip.user.first_name %><br/>
  La ville de l'auteur : <%= @gossip.user.city.name %> <br> <br>
  Le titre : <%= @gossip.title %><br/>
  Créé le : <%= @gossip.created_at.strftime('%d/%m/%Y') %><br/>
  Le contenu du potin : <%= @gossip.content %><br><br>

  <%= link_to "Page de l'auteur", user_path(@gossip.user.id), class: "btn btn-primary" %> 
    
  <%= link_to "Editer le gossip", edit_gossip_path(@gossip.id), class: "btn btn-primary" %> 
    

  <a href= "<%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-confirm="Êtes-vous sur de vouloir supprimer ce gossip ?"
  data-method="DELETE">Supprimer le gossip</a><br /><br />

  <h3>Commentaires : </h3><br>

    <p> <% @gossip.comments.each do |comment|%>
    <%= comment.user.first_name %> : <br> <%= comment.content %><br> <br>
    <%end%>
    </p>    
    
    
 <h3>Ajouter un commentaire</h3>


<form action= <%= root_path %> method="POST">
<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
Commentaire : <input class="form-control" type="text" name="comment"><br />
  <input type="submit" class="btn btn-primary" value="Envoyer">
</form>
  </p>