config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#home'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get 'welcome/:first_name', to: 'dynamic#welcome', as: 'welcome_first_name'
  get 'home/:id', to: 'dynamic#user', as: 'user'
  
  resources :gossips
  resources :cities
  resources :comments
  resources :users, only:[:new,:create,:show]
  resources :sessions, only:[:new,:create,:destroy]
end

app/controllers/dynamic_controller.rb
class DynamicController < ApplicationController
  
  def welcome
  end
  
  def user
    @user = User.find(params[:id])
    @city = City.find(params[:id])
  end

end

app/views/dynamic/gossip.html.erb
<br> <br><h2>PAGE POTIN </h2>

<br>
  <p> Voici le potin n° <%= @gossip.id%><br/><br>
  L'auteur : <%= @gossip.user.first_name %><br/>
  Le titre : <%= @gossip.title %><br/>
  Créé le : <%= @gossip.created_at.strftime('%d/%m/%Y') %><br/>
  Le contenu du potin : <%= @gossip.content %><br><br>

  <a class="btn btn-primary btn-sm" href="user/<%= @gossip.id %>" role="button"> Clique pour voir le profil de l'utilisateur </a><br><br>
  
  </p>

app/views/dynamic/user.html.erb
<h2>PAGE USER </h2>



  <p> Voici le profil de l'utilisateur <%= @user.first_name%><br/> <br>
  Prénom : <%= @user.first_name%> <br>
  Nom : <%= @user.last_name%> <br>
  Description : <%= @user.description %><br/>
  Age : <%= @user.age %><br/>
  Email : <%= @user.email %> <br>
  Ville : <%= @user.city.name %><br/><br> 
    
  <%= link_to "Page de la ville", city_path(@user.city.id), class: "btn btn-primary" %> <br><br><br><hr/><br><br><br><hr/>
  
  </p>

app/views/dynamic/welcome.html.erb
<h1> Bienvenue <%= params[:first_name] %> </h1>

<p>J'espère que le site te plait.</p>