config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#home'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get 'welcome/:first_name', to: 'dynamic#welcome', as: 'welcome_first_name'
  get 'home/:id', to: 'dynamic#user', as: 'user'
  
  resources :gossips
  resources :cities
  resources :comments
  resources :users, only:[:new,:create,:show]
  resources :sessions, only:[:new,:create,:destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
  </head>

  
  <body>
    
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
       <%= link_to "Gossip Project", root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Accueil", root_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to "Team", team_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Contact", contact_path, class:"nav-link" %>
        </li>
        
      </ul>
      
      <ul  class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item"> Vous êtes connecté au compte de <%= current_user.first_name %></li>
          <li class="nav-item"><%= link_to "Se déconnecter", session_path(session.id), method: :delete, class:"nav-link" %></li>

        <% else %>
          <li class="nav-item"> <%= link_to "S'enregistrer", new_user_path,   class:"nav-link" %> </li>
          <li class="nav-item"> <%= link_to "Se connecter", new_session_path, class:"nav-link" %> </li>
        <% end %>
        
      </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>